-- MySQL Script generated by MySQL Workbench
-- Sat Oct 29 20:58:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EJERCICIO_4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EJERCICIO_4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EJERCICIO_4` DEFAULT CHARACTER SET utf8 ;
USE `EJERCICIO_4` ;

-- -----------------------------------------------------
-- Table `EJERCICIO_4`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJERCICIO_4`.`Login` (
  `idLogin` INT NOT NULL,
  `Usuario` NVARCHAR(50) NOT NULL,
  `contrasena` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
